version: '3'

services:

  cloudsql-proxy:
    container_name: cloudsqlproxy
    build: .
    environment:
      GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY
      CLOUDSQL_CONNECTION_NAME: $CLOUDSQL_CONNECTION_NAME
    ports:
      - "3306:3306"
